(dp1
S'output'
p2
S'<type \'exceptions.RuntimeError\'> Failure to connect, tried 5 times:\nTraceback (most recent call last):\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 446, in __init__\n    self._adapter = ADAPTERS[self._dbname](**kwargs)\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 60, in __call__\n    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\postgres.py", line 155, in __init__\n    self.reconnect()\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\connection.py", line 125, in reconnect\n    self.connection = f()\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\postgres.py", line 152, in connector\n    return self.driver.connect(**driver_args)\n  File "psycopg2/__init__.py", line 164, in connect\nOperationalError: could not connect to server: Connection refused (0x0000274D/10061)\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused (0x0000274D/10061)\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n\n'
p3
sS'layer'
p4
S'C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\applications\\SistemaPIO\\models\\db.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\n# -------------------------------------------------------------------------\n# This scaffolding model makes your app work on Google App Engine too\n# File is released under public domain and you can use without limitations\n# -------------------------------------------------------------------------\n\nif request.global_settings.web2py_version < "2.14.1":\n    raise HTTP(500, "Requires web2py 2.13.3 or newer")\n\n# -------------------------------------------------------------------------\n# if SSL/HTTPS is properly configured and you want all HTTP requests to\n# be redirected to HTTPS, uncomment the line below:\n# -------------------------------------------------------------------------\n# request.requires_https()\n\n# -------------------------------------------------------------------------\n# app configuration made easy. Look inside private/appconfig.ini\n# -------------------------------------------------------------------------\nfrom gluon.contrib.appconfig import AppConfig\n\n# -------------------------------------------------------------------------\n# once in production, remove reload=True to gain full speed\n# -------------------------------------------------------------------------\nmyconf = AppConfig(reload=True)\n\nif not request.env.web2py_runtime_gae:\n    # ---------------------------------------------------------------------\n    # if NOT running on Google App Engine use SQLite or other DB\n    # ---------------------------------------------------------------------\n    db = DAL(\'postgres://SisPIO:SisPIO@localhost/SisPIO\', pool_size = 10)\nelse:\n    # ---------------------------------------------------------------------\n    # connect to Google BigTable (optional \'google:datastore://namespace\')\n    # ---------------------------------------------------------------------\n    db = DAL(\'google:datastore+ndb\')\n    # ---------------------------------------------------------------------\n    # store sessions and tickets there\n    # ---------------------------------------------------------------------\n    session.connect(request, response, db=db)\n    # ---------------------------------------------------------------------\n    # or store session in Memcache, Redis, etc.\n    # from gluon.contrib.memdb import MEMDB\n    # from google.appengine.api.memcache import Client\n    # session.connect(request, response, db = MEMDB(Client()))\n    # ---------------------------------------------------------------------\n\n# -------------------------------------------------------------------------\n# by default give a view/generic.extension to all actions from localhost\n# none otherwise. a pattern can be \'controller/function.extension\'\n# -------------------------------------------------------------------------\nresponse.generic_patterns = [\'*\'] if request.is_local else []\n# -------------------------------------------------------------------------\n# choose a style for forms\n# -------------------------------------------------------------------------\nresponse.formstyle = myconf.get(\'forms.formstyle\')  # or \'bootstrap3_stacked\' or \'bootstrap2\' or other\nresponse.form_label_separator = myconf.get(\'forms.separator\') or \'\'\n\n# -------------------------------------------------------------------------\n# (optional) optimize handling of static files\n# -------------------------------------------------------------------------\n# response.optimize_css = \'concat,minify,inline\'\n# response.optimize_js = \'concat,minify,inline\'\n\n# -------------------------------------------------------------------------\n# (optional) static assets folder versioning\n# -------------------------------------------------------------------------\n# response.static_version = \'0.0.0\'\n\n# -------------------------------------------------------------------------\n# Here is sample code if you need for\n# - email capabilities\n# - authentication (registration, login, logout, ... )\n# - authorization (role based authorization)\n# - services (xml, csv, json, xmlrpc, jsonrpc, amf, rss)\n# - old style crud actions\n# (more options discussed in gluon/tools.py)\n# -------------------------------------------------------------------------\n\nfrom gluon.tools import Auth, Service, PluginManager\n\n# host names must be a list of allowed host names (glob syntax allowed)\nauth = Auth(db, host_names=myconf.get(\'host.names\'))\nservice = Service()\nplugins = PluginManager()\n\n# -------------------------------------------------------------------------\n# create all tables needed by auth if not custom tables\n# -------------------------------------------------------------------------\nauth.settings.table_user_name = \'usuario\'\n\ndb.define_table(\n    auth.settings.table_user_name,\n    Field(\'nombre\', length=128, default=\'\'),\n    Field(\'apellido\', length=128, default=\'\'),\n    Field(\'email\', length=128, default=\'\'),\n    Field(\'ci\', length=8, default=\'\', unique=True),  # Requerido\n    Field(\'password\', \'password\', length=512,            # Requerido\n          readable=False, label=\'Clave\'),\n    Field(\'registration_key\', length=512,                # Requerido\n          writable=False, readable=False, default=\'\'),\n    Field(\'reset_password_key\', length=512,              # Requerido\n          writable=False, readable=False, default=\'\'),\n    Field(\'registration_id\', length=512,                 # Requerido\n          writable=False, readable=False, default=\'\')\n    )\n\n## Validadores\nnuevaTablaUsuario = db[auth.settings.table_user_name] \nnuevaTablaUsuario.nombre.requires =   IS_NOT_EMPTY(error_message=auth.messages.is_empty)\nnuevaTablaUsuario.apellido.requires =   IS_NOT_EMPTY(error_message=auth.messages.is_empty)\nnuevaTablaUsuario.password.requires = [CRYPT()]\nnuevaTablaUsuario.email.requires = [IS_EMAIL(error_message=auth.messages.invalid_email)]\nnuevaTablaUsuario.ci.requires = [IS_NOT_IN_DB(db, nuevaTablaUsuario.ci)]\n\nauth.settings.table_user = nuevaTablaUsuario \nauth.define_tables(username = True, signature = False)\n\nauth.settings.create_user_groups = None\n\n# -------------------------------------------------------------------------\n# configure email\n# -------------------------------------------------------------------------\nmail = auth.settings.mailer\nmail.settings.server = \'logging\' if request.is_local else myconf.get(\'smtp.server\')\nmail.settings.sender = \'proppio@usb.ve\'\nmail.settings.login = myconf.get(\'smtp.login\')\nmail.settings.tls = myconf.get(\'smtp.tls\') or False\nmail.settings.ssl = myconf.get(\'smtp.ssl\') or False\n\n# -------------------------------------------------------------------------\n# configure auth policy\n# -------------------------------------------------------------------------\nauth.settings.registration_requires_verification = False\nauth.settings.registration_requires_approval = False\nauth.settings.reset_password_requires_verification = True\n\n# -------------------------------------------------------------------------\n# Define your tables below (or better in another model file) for example\n#\n# >>> db.define_table(\'mytable\', Field(\'myfield\', \'string\'))\n#\n# Fields can be \'string\',\'text\',\'password\',\'integer\',\'double\',\'boolean\'\n#       \'date\',\'time\',\'datetime\',\'blob\',\'upload\', \'reference TABLENAME\'\n# There is an implicit \'id integer autoincrement\' field\n# Consult manual for more options, validators, etc.\n#\n# More API examples for controllers:\n#\n# >>> db.mytable.insert(myfield=\'value\')\n# >>> rows = db(db.mytable.myfield == \'value\').select(db.mytable.ALL)\n# >>> for row in rows: print row.id, row.myfield\n# -------------------------------------------------------------------------\n\n# -------------------------------------------------------------------------\n# after defining tables, uncomment below to enable auditing\n# -------------------------------------------------------------------------\n# auth.enable_record_versioning(db)\n\ndb.define_table(\n    \'liceo\',\n    Field(\'id\', unique=True, notnull=True),\n    Field(\'nombre\', \'string\', notnull=True),\n    Field(\'tipo\', \'string\', notnull=True),\n\n    primarykey=[\'id\']\n    )\n\ndb.define_table(\n    \'estudiante\',\n    Field(\'ci\', length=8, type=\'reference usuario\', notnull=True, unique=True),\n    Field(\'promedio\', \'integer\', notnull=True),\n    Field(\'direccion\', \'string\'),\n    Field(\'fecha_nacimiento\', \'date\'),\n    Field(\'sexo\', \'string\', length=1),\n    Field(\'estatus\', \'string\'),\n    Field(\'cohorte\', \'string\'),\n    Field(\'eximido\', \'boolean\'),\n    Field(\'ci_representante\', \'string\', length=8),\n    Field(\'nombre_representante\', \'string\'),\n    Field(\'apellido_representante\', \'string\'),\n    Field(\'correo_representante\', \'string\', length=128, required=True, requires=IS_EMAIL(error_message=auth.messages.invalid_email)),\n    Field(\'direccion_representante\', \'string\'),\n    Field(\'id_liceo\', \'reference liceo.id\')\n    )\n\ndb.define_table(\n    \'profesor\',\n    Field(\'ci\', length=8, type=\'reference usuario\', notnull=True, unique=True)\n    )\n\ndb.define_table(\n    \'representante_sede\',\n    Field(\'ci\', length=8, type=\'reference usuario\', notnull=True, unique=True),\n    Field(\'sede\', \'string\')\n    )\n\ndb.define_table(\n    \'representante_liceo\',\n    Field(\'ci\', length=8, type=\'reference usuario\', notnull=True, unique=True),\n    Field(\'id_liceo\', \'reference liceo.id\')\n    )\n\n\ndb.define_table(\n    \'materia\',\n    Field(\'id\', \'integer\', length=128, unique=True, notnull=True),\n    Field(\'nombre\', \'string\', notnull=True),\n    Field(\'ci_estudiante\', \'reference estudiante\'),\n    Field(\'ci_profesor\', \'reference profesor\')\n    )\n\ndb.define_table(\n    \'carrera\',\n    Field(\'id\', unique=True, notnull=True),\n    Field(\'nombre\', \'string\')\n    )'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\applications\\SistemaPIO\\models\\db.py", line 31, in <module>\n    db = DAL(\'postgres://SisPIO:SisPIO@localhost/SisPIO\', pool_size = 10)\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 174, in __call__\n    obj = super(MetaDAL, cls).__call__(*args, **kwargs)\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 473, in __init__\n    "Failure to connect, tried %d times:\\n%s" % (attempts, tb)\nRuntimeError: Failure to connect, tried 5 times:\nTraceback (most recent call last):\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 446, in __init__\n    self._adapter = ADAPTERS[self._dbname](**kwargs)\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 60, in __call__\n    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\postgres.py", line 155, in __init__\n    self.reconnect()\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\connection.py", line 125, in reconnect\n    self.connection = f()\n  File "C:\\Users\\Rafael Cisneros\\Desktop\\web2py\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\postgres.py", line 152, in connector\n    return self.driver.connect(**driver_args)\n  File "psycopg2/__init__.py", line 164, in connect\nOperationalError: could not connect to server: Connection refused (0x0000274D/10061)\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused (0x0000274D/10061)\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n\n\n'
p11
s.